### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by pmtp** [jobapis/jobs-stackoverflow#1]
In your documentation,

`$client = new JobApis\Jobs\Client\Provider\StackoverflowProvider($query);`

should be 

$client = new JobApis\Jobs\Client\Provider**s**\StackoverflowProvider($query);

However this package was exactly what i was looking for

**Comment by karllhughes** [comment]
@pmtp thanks for reporting the issue and I'm glad to hear this package is helpful. If you haven't seen it already, you may want to check out [Jobs Multi](https://github.com/jobapis/jobs-multi), which lets you connect with multiple job boards in one single client.

I'll make the doc update today.
